services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=contadb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'PGDATA: /data/postgres'
    ports:
      - '5432'
